### ISSUE TITLE
Deprecated token endpoint URL being used

### ISSUE THREAD

**Issue by bzswords** [kolanos/dwolla-v2-go#4]
After talking with support at Dwolla, it looks like the Token URL's used in this package are out of date. If you go here: https://developers.dwolla.com/resources/changelog.html and go to 2019-02-21 you'll see a note about the new dwolla token exchange endpoint being https://api.dwolla.com/token (sandbox: https://api-sandbox.dwolla.com/token) rather than https://accounts.dwolla.com/token.

https://github.com/kolanos/dwolla-v2-go/blob/master/client.go#L34

![Screen Shot 2020-03-26 at 5 27 39 PM](https://user-images.githubusercontent.com/5658690/77698631-537a1800-6f87-11ea-9c4e-58e15d998c22.png)

Would be happy to make the change and cut a PR if given access.

**Comment by kolanos** [comment]
@bzswords You have access. Click the "Fork" button and create a fork. You can submit a PR back to this repo from your fork.
