### ISSUE TITLE
Include embedded errors list in error response

### ISSUE THREAD

**Issue by castlesb** [kolanos/dwolla-v2-go#6]
We have been running into validation errors integrating with Dwolla but it is difficult to debug since the embedded errors list does not get returned.
```
Error creating funding source","error":"[ValidationError] Validation error(s) present. See embedded errors list for more details."
```
Can there be a change here to include the embedded errors in the validation errors response?
https://github.com/kolanos/dwolla-v2-go/blob/master/hal.go#L33

**Comment by kolanos** [comment]
@castlesb Does this not contain the embedded errors? https://github.com/kolanos/dwolla-v2-go/blob/master/hal.go#L28

Pull requests welcome.
