### ISSUE TITLE
CreateDocument functions do not return ValidationErrors

### ISSUE THREAD

**Issue by bnguyen88** [kolanos/dwolla-v2-go#7]
I have been receiving ValidationError codes from customer.CreateDocument and beneficialOwner.CreateDocument but the error returned is not of type `ValidationError`. Please consider adding this error type so that users can debug their requests

**Comment by kolanos** [comment]
Hi bnguyen88, thanks for the issue. There is a `HALError` type which you can check, it is returned here: https://github.com/kolanos/dwolla-v2-go/blob/master/client.go#L491

Does that not work in your case?

**Comment by bnguyen88** [comment]
@kolanos thanks for the quick reply! unfortunately the useful part of the ValidationError is inside of the `Embedded` field which isn't captured in a normal `HALError`
